# Generated by Django 3.2.4 on 2021-06-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_elo', models.IntegerField()),
                ('black_elo', models.IntegerField()),
                ('pgn', models.CharField(max_length=10000)),
                ('game_link', models.CharField(max_length=10000)),
            ],
        ),
    ]
