# Generated by Django 3.2.4 on 2021-06-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessergame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='average_elo',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
